import { Lead, User, ChecklistQuestion, AppSettings, CallRecord, Campaign } from '../types';
import { DEFAULT_CHECKLIST_QUESTIONS } from '../constants/defaultChecklist';

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp_meta_1',
    name: 'PM Surya Ghar - Kolkata Rooftop Meta',
    source: 'Meta',
    status: 'Active',
    sheetUrl: '',
    columnMapping: {
      name: 'Full Name',
      phone: 'Phone Number',
      email: 'Email',
      city: 'City',
      address: 'Address',
      pinCode: 'Postal Code',
      notes: 'Monthly Bill',
    },
    assignedTelecallerIds: ['usr_tc_1', 'usr_tc_2'],
    assignmentMode: 'round_robin',
    autoSync: false,
    syncInterval: 5,
    lastSyncedAt: new Date(Date.now() - 3600000).toISOString(),
    startDate: '2026-03-01',
    createdAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'camp_google_1',
    name: 'West Bengal Solar Subsidy 78k Google Ads',
    source: 'Google',
    status: 'Active',
    sheetUrl: '',
    columnMapping: {
      name: 'Customer Name',
      phone: 'Mobile',
      email: 'Email Address',
      city: 'District',
      address: 'Location',
      pinCode: 'PIN',
      notes: 'Requirement',
    },
    assignedTelecallerIds: ['usr_tc_1', 'usr_tc_2'],
    assignmentMode: 'round_robin',
    autoSync: false,
    syncInterval: 15,
    lastSyncedAt: new Date(Date.now() - 7200000).toISOString(),
    startDate: '2026-03-10',
    createdAt: '2026-03-10T00:00:00.000Z',
  },
];

// Known SHA-256 hashes:
// "admin123" -> "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9"
// "bo123" -> "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92" (example or will re-verify)

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_admin_1',
    name: 'Debashis Mukherjee (Admin)',
    username: 'admin',
    passwordHash: '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', // admin123
    role: 'admin',
    active: true,
    phone: '9830112233',
    mustChangePassword: true, // Default admin prompt
  },
  {
    id: 'usr_bo_1',
    name: 'Priyanka Sen (Ops)',
    username: 'backoffice',
    passwordHash: '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', // admin123 for demo convenience
    role: 'backoffice',
    active: true,
    phone: '9830223344',
    mustChangePassword: false,
  },
  {
    id: 'usr_tc_1',
    name: 'Ananya Roy',
    username: 'ananya',
    passwordHash: '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
    role: 'telecaller',
    active: true,
    phone: '9830334455',
    mustChangePassword: false,
  },
  {
    id: 'usr_tc_2',
    name: 'Sourav Das',
    username: 'sourav',
    passwordHash: '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
    role: 'telecaller',
    active: true,
    phone: '9830445566',
    mustChangePassword: false,
  },
  {
    id: 'usr_sv_1',
    name: 'Rajesh Karmakar',
    username: 'rajesh',
    passwordHash: '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
    role: 'surveyor',
    active: true,
    phone: '9830556677',
    mustChangePassword: false,
  },
  {
    id: 'usr_sv_2',
    name: 'Bikram Paul',
    username: 'bikram',
    passwordHash: '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
    role: 'surveyor',
    active: true,
    phone: '9830667788',
    mustChangePassword: false,
  },
];

export const INITIAL_SETTINGS: AppSettings = {
  companyName: 'Green View Agrotech',
  tagline: 'Greening Your Life',
  autoAssignEnabled: true,
  adSheetUrl: '',
  adSheetAutoSync: false,
  adSheetSyncInterval: 5,
  adSheetLastSynced: '',
  adSheetColumnMapping: {
    name: 'Full Name',
    phone: 'Phone Number',
    email: 'Email',
    campaign: 'Campaign Name',
    source: 'Platform',
  },
  webAppUrl: '',
  secretKey: 'GVA_SOLAR_SECRET_2026',
};

// Sample demo audio link (freely accessible reliable clean audio)
const SAMPLE_AUDIO_URL = 'https://actions.google.com/sounds/v1/telephones/telephone_touch_tone.ogg';

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead_101',
    name: 'Subrata Banerjee',
    phone: '9831201940',
    email: 'subrata.banerjee@gmail.com',
    campaign: 'Kolkata 3kW PM Surya Ghar Subsidy',
    source: 'Meta',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    assignedTelecallerId: 'usr_tc_1',
    assignedTelecallerName: 'Ananya Roy',
    status: 'CONFIRMED',
    notes: 'Customer has 450 sq ft RCC roof in Salt Lake Sector 2. Monthly electricity bill ₹4,200. Very eager for 3kW On-Grid with ₹78,000 subsidy. All family members will be available.',
    surveyDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    surveyTime: '11:00 AM',
    address: 'FD-142, Sector 3, Salt Lake City, Near Karunamoyee',
    pinCode: '700091',
    assignedSurveyorId: 'usr_sv_1',
    assignedSurveyorName: 'Rajesh Karmakar',
    surveyStatus: 'Scheduled',
    callAttempts: 1,
    checklistAnswers: {
      q1: true,
      q2: true,
      q3: true,
      q4: false, // On-grid
      q5: true,
      q6: true,
      q7: true,
      q8: true,
      q9: true,
      q10: true,
      q11: true,
      q12: true,
      q13: true,
      q14: true,
      q15: true,
      q16: true,
      q17: true,
      q18: true,
      q19: true,
      q20: true,
      q21: true,
      q22: true,
      q23: true,
    },
    callHistory: [
      {
        id: 'call_101_1',
        leadId: 'lead_101',
        leadName: 'Subrata Banerjee',
        phone: '9831201940',
        timestamp: new Date(Date.now() - 3600000 * 1.5).toISOString(),
        duration: 215,
        status: 'CONFIRMED',
        notes: 'Detailed discussion about PM Surya Ghar 3kW package. Customer confirmed RCC roof and domestic meter.',
        telecallerId: 'usr_tc_1',
        telecallerName: 'Ananya Roy',
        recordingUrl: SAMPLE_AUDIO_URL,
      },
    ],
  },
  {
    id: 'lead_102',
    name: 'Dr. Amitabha Ghosh',
    phone: '9830561234',
    email: 'dr.ghosh.kol@yahoo.com',
    campaign: 'South Kolkata Rooftop Solar Special',
    source: 'Google',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    assignedTelecallerId: 'usr_tc_1',
    assignedTelecallerName: 'Ananya Roy',
    status: 'CONFIRMED',
    notes: '2-storey independent villa in Jadavpur. Requested survey on Sunday afternoon. Wants battery backup (Hybrid) due to occasional clinic load.',
    surveyDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    surveyTime: '03:30 PM',
    address: '42/B, Central Road, Jadavpur, Kolkata',
    pinCode: '700032',
    assignedSurveyorId: 'usr_sv_2',
    assignedSurveyorName: 'Bikram Paul',
    surveyStatus: 'Scheduled',
    callAttempts: 1,
    checklistAnswers: {
      q1: true,
      q2: true,
      q3: true,
      q4: true, // Hybrid
      q5: true,
      q6: true,
      q7: true,
      q8: true,
      q9: true,
      q10: true,
      q11: true,
      q12: true,
      q13: true,
      q14: true,
      q15: true,
      q16: true,
      q17: true,
      q18: true,
      q19: true,
      q20: true,
      q21: true,
      q22: true,
      q23: true,
    },
    callHistory: [
      {
        id: 'call_102_1',
        leadId: 'lead_102',
        leadName: 'Dr. Amitabha Ghosh',
        phone: '9830561234',
        timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
        duration: 180,
        status: 'CONFIRMED',
        notes: 'Agreed for hybrid 5kW system. Survey scheduled for Sunday.',
        telecallerId: 'usr_tc_1',
        telecallerName: 'Ananya Roy',
      },
    ],
  },
  {
    id: 'lead_103',
    name: 'Manoj Kumar Agarwal',
    phone: '9832145678',
    email: 'm.agarwal@gmail.com',
    campaign: 'Howrah Residential Solar Scheme',
    source: 'Meta',
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    assignedTelecallerId: 'usr_tc_2',
    assignedTelecallerName: 'Sourav Das',
    status: 'FOLLOW_UP',
    callbackDate: new Date().toISOString().split('T')[0],
    callbackTime: '05:00 PM',
    notes: 'In meeting right now. Asked to call back after 5 PM today. Very keen on saving electricity bill.',
    callAttempts: 1,
    callHistory: [
      {
        id: 'call_103_1',
        leadId: 'lead_103',
        leadName: 'Manoj Kumar Agarwal',
        phone: '9832145678',
        timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
        duration: 45,
        status: 'FOLLOW_UP',
        notes: 'Asked for callback after office hours at 5 PM.',
        telecallerId: 'usr_tc_2',
        telecallerName: 'Sourav Das',
      },
    ],
  },
  {
    id: 'lead_104',
    name: 'Tanmoy Sen',
    phone: '9748123450',
    email: 'tanmoysen.wb@gmail.com',
    campaign: 'Bardhaman Solar Subsidy Drive',
    source: 'Meta',
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    assignedTelecallerId: 'usr_tc_2',
    assignedTelecallerName: 'Sourav Das',
    status: 'HOT',
    notes: 'Owns 3kW requirement. Ready to share electricity bill on WhatsApp. Discussing with elder brother.',
    callAttempts: 1,
    callHistory: [
      {
        id: 'call_104_1',
        leadId: 'lead_104',
        leadName: 'Tanmoy Sen',
        phone: '9748123450',
        timestamp: new Date(Date.now() - 3600000 * 7).toISOString(),
        duration: 154,
        status: 'HOT',
        notes: 'Explained PM Surya Ghar ₹78,000 direct bank transfer subsidy. Awaiting bill photo.',
        telecallerId: 'usr_tc_2',
        telecallerName: 'Sourav Das',
      },
    ],
  },
  {
    id: 'lead_105',
    name: 'Smt. Rina Chakraborty',
    phone: '9433129876',
    campaign: 'Kolkata 3kW PM Surya Ghar Subsidy',
    source: 'Meta',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    assignedTelecallerId: 'usr_tc_1',
    assignedTelecallerName: 'Ananya Roy',
    status: 'NO_ANSWER',
    notes: 'Ringing, but no response. 2 attempts made.',
    callAttempts: 2,
  },
  {
    id: 'lead_106',
    name: 'Pradeep Mondal',
    phone: '9163456789',
    campaign: 'Durgapur Industrial & Home Solar',
    source: 'Google',
    createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    assignedTelecallerId: 'usr_tc_2',
    assignedTelecallerName: 'Sourav Das',
    status: 'SWITCHED_OFF',
    notes: 'Mobile was switched off when dialed in morning.',
    callAttempts: 1,
  },
  {
    id: 'lead_107',
    name: 'Alok Nath Dutta',
    phone: '9836789012',
    campaign: 'Kolkata Rooftop Solar 2026',
    source: 'Meta',
    createdAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    assignedTelecallerId: 'usr_tc_1',
    assignedTelecallerName: 'Ananya Roy',
    status: 'CONFIRMED',
    notes: 'Survey completed successfully yesterday. Customer verified roof structure and agreed for 4kW Mono PERC setup.',
    surveyDate: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    surveyTime: '01:00 PM',
    address: '18/1, Gariahat Road, Ballygunge, Kolkata',
    pinCode: '700019',
    assignedSurveyorId: 'usr_sv_1',
    assignedSurveyorName: 'Rajesh Karmakar',
    surveyStatus: 'Completed',
    surveyNotes: 'Site feasible. 420 sq ft shadow-free RCC roof. Sanctioned load 5kW domestic. Meter replacement required from WBSEDCL. Passed to quotation team.',
    checklistAnswers: {
      q1: true,
      q2: true,
      q3: true,
      q4: false,
      q5: true,
      q6: true,
      q7: true,
      q8: true,
      q9: true,
      q10: true,
      q11: true,
      q12: true,
      q13: true,
      q14: true,
      q15: true,
      q16: true,
      q17: true,
      q18: true,
      q19: true,
      q20: true,
      q21: true,
      q22: true,
      q23: true,
    },
    callHistory: [
      {
        id: 'call_107_1',
        leadId: 'lead_107',
        leadName: 'Alok Nath Dutta',
        phone: '9836789012',
        timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
        duration: 310,
        status: 'CONFIRMED',
        notes: 'Confirmed site inspection appointment.',
        telecallerId: 'usr_tc_1',
        telecallerName: 'Ananya Roy',
      },
    ],
  },
  {
    id: 'lead_108',
    name: 'Debabrata Mukherjee',
    phone: '9874112299',
    campaign: 'Siliguri North Bengal Solar Mission',
    source: 'Meta',
    createdAt: new Date(Date.now() - 3600000 * 26).toISOString(),
    assignedTelecallerId: 'usr_tc_2',
    assignedTelecallerName: 'Sourav Das',
    status: 'CONFIRMED',
    notes: 'Awaiting surveyor assignment by back office. Address is in Hakimpara, Siliguri.',
    surveyDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    surveyTime: '02:00 PM',
    address: 'Ward 15, Hakimpara, Near Children Park, Siliguri',
    pinCode: '734001',
    surveyStatus: 'Pending',
    checklistAnswers: {
      q1: true,
      q2: true,
      q3: true,
      q4: false,
      q5: true,
      q6: true,
      q7: true,
      q8: true,
      q9: true,
      q10: true,
      q11: true,
      q12: true,
      q13: true,
      q14: true,
      q15: true,
      q16: true,
      q17: true,
      q18: true,
      q19: true,
      q20: true,
      q21: true,
      q22: true,
      q23: true,
    },
    callHistory: [
      {
        id: 'call_108_1',
        leadId: 'lead_108',
        leadName: 'Debabrata Mukherjee',
        phone: '9874112299',
        timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
        duration: 240,
        status: 'CONFIRMED',
        notes: 'Customer answered all checklist questions. Needs surveyor visit.',
        telecallerId: 'usr_tc_2',
        telecallerName: 'Sourav Das',
      },
    ],
  },
  {
    id: 'lead_109',
    name: 'Kallol Majumdar',
    phone: '9007654321',
    campaign: 'South Kolkata Rooftop Solar Special',
    source: 'Google',
    createdAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    assignedTelecallerId: 'usr_tc_1',
    assignedTelecallerName: 'Ananya Roy',
    status: 'LOW_BILL',
    notes: 'Average monthly electricity consumption is only ₹450 (1 fan + 2 LED bulbs). Solar system not financially viable. Customer was politely advised.',
    callAttempts: 1,
  },
  {
    id: 'lead_110',
    name: 'Suresh Kumar Gupta',
    phone: '9830099881',
    campaign: 'Howrah Residential Solar Scheme',
    source: 'Meta',
    createdAt: new Date(Date.now() - 3600000 * 40).toISOString(),
    assignedTelecallerId: 'usr_tc_2',
    assignedTelecallerName: 'Sourav Das',
    status: 'NO_ROOF',
    notes: 'Tenant staying on 3rd floor. Landlord refuses permission for solar panels on common roof.',
    callAttempts: 1,
  },
];

export const INITIAL_CALLS: CallRecord[] = [
  {
    id: 'call_101_1',
    leadId: 'lead_101',
    leadName: 'Subrata Banerjee',
    phone: '9831201940',
    timestamp: new Date(Date.now() - 3600000 * 1.5).toISOString(),
    duration: 215,
    status: 'CONFIRMED',
    notes: 'Detailed discussion about PM Surya Ghar 3kW package. Customer confirmed RCC roof and domestic meter.',
    telecallerId: 'usr_tc_1',
    telecallerName: 'Ananya Roy',
    recordingUrl: SAMPLE_AUDIO_URL,
  },
  {
    id: 'call_102_1',
    leadId: 'lead_102',
    leadName: 'Dr. Amitabha Ghosh',
    phone: '9830561234',
    timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
    duration: 180,
    status: 'CONFIRMED',
    notes: 'Agreed for hybrid 5kW system. Survey scheduled for Sunday.',
    telecallerId: 'usr_tc_1',
    telecallerName: 'Ananya Roy',
  },
  {
    id: 'call_103_1',
    leadId: 'lead_103',
    leadName: 'Manoj Kumar Agarwal',
    phone: '9832145678',
    timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
    duration: 45,
    status: 'FOLLOW_UP',
    notes: 'Asked for callback after office hours at 5 PM.',
    telecallerId: 'usr_tc_2',
    telecallerName: 'Sourav Das',
  },
  {
    id: 'call_104_1',
    leadId: 'lead_104',
    leadName: 'Tanmoy Sen',
    phone: '9748123450',
    timestamp: new Date(Date.now() - 3600000 * 7).toISOString(),
    duration: 154,
    status: 'HOT',
    notes: 'Explained PM Surya Ghar ₹78,000 direct bank transfer subsidy. Awaiting bill photo.',
    telecallerId: 'usr_tc_2',
    telecallerName: 'Sourav Das',
  },
  {
    id: 'call_107_1',
    leadId: 'lead_107',
    leadName: 'Alok Nath Dutta',
    phone: '9836789012',
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
    duration: 310,
    status: 'CONFIRMED',
    notes: 'Confirmed site inspection appointment.',
    telecallerId: 'usr_tc_1',
    telecallerName: 'Ananya Roy',
  },
  {
    id: 'call_108_1',
    leadId: 'lead_108',
    leadName: 'Debabrata Mukherjee',
    phone: '9874112299',
    timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
    duration: 240,
    status: 'CONFIRMED',
    notes: 'Customer answered all checklist questions. Needs surveyor visit.',
    telecallerId: 'usr_tc_2',
    telecallerName: 'Sourav Das',
  },
];

export function getInitialChecklistQuestions(): ChecklistQuestion[] {
  return [...DEFAULT_CHECKLIST_QUESTIONS];
}
