import { StatusConfig, StatusCategory } from '../types';

export const DEFAULT_STATUSES: StatusConfig[] = [
  // Positive (Green / Orange)
  {
    code: 'CONFIRMED',
    label: 'Confirmed',
    category: 'positive',
    color: '#15803D',
    bgColor: 'bg-emerald-50 text-emerald-800 border-emerald-200',
    textColor: 'text-emerald-700',
    description: 'Site survey agreed and booked with customer',
  },
  {
    code: 'HOT',
    label: 'Hot Lead',
    category: 'positive',
    color: '#EA580C',
    bgColor: 'bg-amber-50 text-amber-800 border-amber-200',
    textColor: 'text-amber-700',
    description: 'Very interested, discussion in progress',
  },

  // Callback (Blue)
  {
    code: 'FOLLOW_UP',
    label: 'Follow Up',
    category: 'callback',
    color: '#2563EB',
    bgColor: 'bg-blue-50 text-blue-800 border-blue-200',
    textColor: 'text-blue-700',
    description: 'Customer requested a callback with scheduled time',
  },
  {
    code: 'CALL_LATER',
    label: 'Call Later',
    category: 'callback',
    color: '#0284C7',
    bgColor: 'bg-sky-50 text-sky-800 border-sky-200',
    textColor: 'text-sky-700',
    description: 'Busy right now, asked to call back later',
  },

  // Not reached (Grey) - stays in queue, increment attempt
  {
    code: 'NO_ANSWER',
    label: 'No Answer',
    category: 'not_reached',
    color: '#64748B',
    bgColor: 'bg-slate-100 text-slate-800 border-slate-200',
    textColor: 'text-slate-600',
    description: 'Ringing but call not picked up',
  },
  {
    code: 'SWITCHED_OFF',
    label: 'Switched Off',
    category: 'not_reached',
    color: '#64748B',
    bgColor: 'bg-slate-100 text-slate-800 border-slate-200',
    textColor: 'text-slate-600',
    description: 'Phone turned off or out of coverage',
  },
  {
    code: 'PART_HEARD',
    label: 'Part Heard',
    category: 'not_reached',
    color: '#64748B',
    bgColor: 'bg-slate-100 text-slate-800 border-slate-200',
    textColor: 'text-slate-600',
    description: 'Call connected but line dropped or voice unclear',
  },

  // Closed or lost (Red)
  {
    code: 'NOT_INTERESTED',
    label: 'Not Interested',
    category: 'closed_lost',
    color: '#DC2626',
    bgColor: 'bg-rose-50 text-rose-800 border-rose-200',
    textColor: 'text-rose-700',
    description: 'Explicitly declined solar rooftop proposal',
  },
  {
    code: 'LOW_BILL',
    label: 'Low Bill',
    category: 'closed_lost',
    color: '#DC2626',
    bgColor: 'bg-rose-50 text-rose-800 border-rose-200',
    textColor: 'text-rose-700',
    description: 'Electricity bill too low for viable ROI (<₹800/mo)',
  },
  {
    code: 'TRUST_ISSUE',
    label: 'Trust Issue',
    category: 'closed_lost',
    color: '#DC2626',
    bgColor: 'bg-rose-50 text-rose-800 border-rose-200',
    textColor: 'text-rose-700',
    description: 'Skeptical of subsidy disbursement or warranties',
  },
  {
    code: 'ALREADY_INSTALLED',
    label: 'Already Installed',
    category: 'closed_lost',
    color: '#DC2626',
    bgColor: 'bg-rose-50 text-rose-800 border-rose-200',
    textColor: 'text-rose-700',
    description: 'Solar panel system already set up at premises',
  },
  {
    code: 'NO_ROOF',
    label: 'No Roof',
    category: 'closed_lost',
    color: '#DC2626',
    bgColor: 'bg-rose-50 text-rose-800 border-rose-200',
    textColor: 'text-rose-700',
    description: 'Tenant or no private rooftop access',
  },
  {
    code: 'PRICE_PROBLEM',
    label: 'Price Problem',
    category: 'closed_lost',
    color: '#DC2626',
    bgColor: 'bg-rose-50 text-rose-800 border-rose-200',
    textColor: 'text-rose-700',
    description: 'Cannot afford down payment or net system cost',
  },
  {
    code: 'RENTED',
    label: 'Rented House',
    category: 'closed_lost',
    color: '#DC2626',
    bgColor: 'bg-rose-50 text-rose-800 border-rose-200',
    textColor: 'text-rose-700',
    description: 'Living in rented property, landlord refuses solar',
  },
  {
    code: 'DROPPED',
    label: 'Dropped',
    category: 'closed_lost',
    color: '#DC2626',
    bgColor: 'bg-rose-50 text-rose-800 border-rose-200',
    textColor: 'text-rose-700',
    description: 'Lost communication or dropped after multiple attempts',
  },

  // Bad lead (Dark grey)
  {
    code: 'INVALID',
    label: 'Invalid Number',
    category: 'bad_lead',
    color: '#475569',
    bgColor: 'bg-slate-200 text-slate-800 border-slate-300',
    textColor: 'text-slate-700',
    description: 'Incorrect telephone digits or non-existent number',
  },
  {
    code: 'WRONG_PERSON',
    label: 'Wrong Person',
    category: 'bad_lead',
    color: '#475569',
    bgColor: 'bg-slate-200 text-slate-800 border-slate-300',
    textColor: 'text-slate-700',
    description: 'Answered by someone else who never applied',
  },
  {
    code: 'DND',
    label: 'DND Requested',
    category: 'bad_lead',
    color: '#475569',
    bgColor: 'bg-slate-200 text-slate-800 border-slate-300',
    textColor: 'text-slate-700',
    description: 'Strict Do Not Disturb request',
  },
  {
    code: 'LANG_BARRIER',
    label: 'Language Barrier',
    category: 'bad_lead',
    color: '#475569',
    bgColor: 'bg-slate-200 text-slate-800 border-slate-300',
    textColor: 'text-slate-700',
    description: 'Requires telecaller with different language (Bengali/Hindi/English)',
  },
];

export const CATEGORY_LABELS: Record<StatusCategory, { label: string; color: string }> = {
  positive: { label: 'Positive', color: 'text-emerald-700 bg-emerald-50 border-emerald-200' },
  callback: { label: 'Callback', color: 'text-blue-700 bg-blue-50 border-blue-200' },
  not_reached: { label: 'Not Reached', color: 'text-slate-700 bg-slate-100 border-slate-200' },
  closed_lost: { label: 'Closed / Lost', color: 'text-rose-700 bg-rose-50 border-rose-200' },
  bad_lead: { label: 'Bad Lead', color: 'text-slate-800 bg-slate-200 border-slate-300' },
};
